import type { Product, ProductVariant, Stock } from "./types";

/* -----------------------------------------------------------
   Variant helpers — keep the data source terse but explicit.
   ----------------------------------------------------------- */
function variants(
  sizes: string[],
  colors: string[],
  outCombos: string[] = [], // "size|color" that are out of stock
  lowCombos: string[] = []
): ProductVariant[] {
  const out: ProductVariant[] = [];
  for (const color of colors) {
    for (const size of sizes) {
      const key = `${size}|${color}`;
      let stock: Stock = "in_stock";
      if (outCombos.includes(key)) stock = "out";
      else if (lowCombos.includes(key)) stock = "low";
      out.push({ size, color, stock });
    }
  }
  return out;
}

const ALPHA = ["XS", "S", "M", "L", "XL", "XXL"];
const ALPHA_KID = ["3-4Y", "5-6Y", "7-8Y", "9-10Y", "11-12Y"];
const SHOE_ADULT = ["6", "7", "8", "9", "10", "11", "12"];
const SHOE_KID = ["10", "11", "12", "13", "1", "2"];
const JEANS = ["28", "30", "32", "34", "36"];

export const products: Product[] = [
  /* ============================ CLOTHING (14) ============================ */
  // --- T-shirts (3) ---
  {
    id: "c01",
    slug: "core-cotton-tee-ecru",
    brand: "Pace Studio",
    name: "Core Cotton Tee",
    productType: "clothing",
    category: "clothing",
    subcategory: "t-shirts",
    gender: "men",
    price: 899,
    compareAtPrice: 1199,
    rating: 4.6,
    reviewCount: 128,
    badge: "sale",
    stock: "in_stock",
    tags: ["basics", "cotton", "everyday", "crew neck"],
    description:
      "A midweight everyday tee cut from combed cotton that holds its shape wash after wash. The clean crew neckline and relaxed body make it the layer you reach for on repeat.",
    features: ["220 GSM combed cotton", "Ribbed crew collar", "Pre-shrunk fabric"],
    images: { main: "/images/products/core-cotton-tee-ecru-a.jpg", alt: "/images/products/core-cotton-tee-ecru-b.jpg" },
    colors: [
      { name: "Ecru", hex: "#e8e2d5" },
      { name: "Ink", hex: "#191919" },
      { name: "Racing Red", hex: "#d64045" },
    ],
    sizeType: "alpha",
    variants: variants(ALPHA, ["Ecru", "Ink", "Racing Red"], ["XS|Racing Red"], ["XXL|Ecru"]),
    clothingExtras: { material: "100% combed cotton", fit: "regular", care: "Machine wash cold, tumble dry low" },
  },
  {
    id: "c02",
    slug: "velocity-dryfit-tee",
    brand: "Velocity",
    name: "Velocity Dry-Fit Training Tee",
    productType: "clothing",
    category: "clothing",
    subcategory: "t-shirts",
    gender: "men",
    price: 1099,
    rating: 4.4,
    reviewCount: 76,
    badge: "new",
    stock: "in_stock",
    tags: ["activewear", "training", "moisture-wicking", "gym"],
    description:
      "Engineered for the gym floor and the morning run, this performance tee wicks sweat and dries fast. Flatlock seams sit flat against the skin so nothing chafes at pace.",
    features: ["Moisture-wicking knit", "Flatlock seams", "Anti-odour finish"],
    images: { main: "/images/products/velocity-dryfit-tee-a.jpg", alt: "/images/products/velocity-dryfit-tee-b.jpg" },
    colors: [
      { name: "Slate", hex: "#5a5f66" },
      { name: "Ink", hex: "#191919" },
    ],
    sizeType: "alpha",
    variants: variants(ALPHA, ["Slate", "Ink"], [], ["S|Slate"]),
    clothingExtras: { material: "88% polyester, 12% elastane", fit: "slim", care: "Machine wash cold, do not iron print" },
  },
  {
    id: "c03",
    slug: "studio-boxy-tee-women",
    brand: "Pace Studio",
    name: "Studio Boxy Tee",
    productType: "clothing",
    category: "clothing",
    subcategory: "t-shirts",
    gender: "women",
    price: 999,
    compareAtPrice: 1299,
    rating: 4.7,
    reviewCount: 94,
    badge: "sale",
    stock: "low",
    tags: ["boxy", "cotton", "oversized", "everyday"],
    description:
      "A dropped-shoulder boxy tee with a slightly cropped hem that pairs as easily with denim as with tailored trousers. Heavyweight cotton gives it a structured, elevated drape.",
    features: ["Heavyweight 240 GSM cotton", "Dropped shoulder", "Cropped boxy hem"],
    images: { main: "/images/products/studio-boxy-tee-women-a.jpg", alt: "/images/products/studio-boxy-tee-women-b.jpg" },
    colors: [
      { name: "Sand", hex: "#d9cbb3" },
      { name: "Ink", hex: "#191919" },
      { name: "Sage", hex: "#8a9083" },
    ],
    sizeType: "alpha",
    variants: variants(["XS", "S", "M", "L", "XL"], ["Sand", "Ink", "Sage"], ["XL|Sage"], ["S|Sand", "M|Sage"]),
    clothingExtras: { material: "100% cotton", fit: "oversized", care: "Machine wash cold, reshape while damp" },
  },
  // --- Shirts (2) ---
  {
    id: "c04",
    slug: "oxford-everyday-shirt",
    brand: "Pace Studio",
    name: "Oxford Everyday Shirt",
    productType: "clothing",
    category: "clothing",
    subcategory: "shirts",
    gender: "men",
    price: 1799,
    rating: 4.5,
    reviewCount: 61,
    stock: "in_stock",
    tags: ["oxford", "cotton", "smart casual", "button-down"],
    description:
      "A button-down Oxford in breathable cotton that moves from desk to dinner without missing a beat. A tailored-but-easy cut keeps it sharp untucked or tucked.",
    features: ["Woven Oxford cotton", "Button-down collar", "Curved shirt-tail hem"],
    images: { main: "/images/products/oxford-everyday-shirt-a.jpg", alt: "/images/products/oxford-everyday-shirt-b.jpg" },
    colors: [
      { name: "Sky", hex: "#b9cdda" },
      { name: "White", hex: "#f4f2ec" },
    ],
    sizeType: "alpha",
    variants: variants(ALPHA, ["Sky", "White"], [], ["XXL|White"]),
    clothingExtras: { material: "100% cotton Oxford weave", fit: "regular", care: "Machine wash warm, iron medium" },
  },
  {
    id: "c05",
    slug: "linen-blend-camp-shirt",
    brand: "Pace Studio",
    name: "Linen-Blend Camp Shirt",
    productType: "clothing",
    category: "clothing",
    subcategory: "shirts",
    gender: "women",
    price: 2099,
    compareAtPrice: 2599,
    rating: 4.8,
    reviewCount: 52,
    badge: "sale",
    stock: "in_stock",
    tags: ["linen", "summer", "camp collar", "breathable"],
    description:
      "A relaxed camp-collar shirt in a cool linen blend built for warm-weather layering. The open revere collar and boxy body give it an effortless resort feel.",
    features: ["Linen-cotton blend", "Camp / revere collar", "Side vents"],
    images: { main: "/images/products/linen-blend-camp-shirt-a.jpg", alt: "/images/products/linen-blend-camp-shirt-b.jpg" },
    colors: [
      { name: "Terracotta", hex: "#c07a54" },
      { name: "Ecru", hex: "#e8e2d5" },
    ],
    sizeType: "alpha",
    variants: variants(["XS", "S", "M", "L", "XL"], ["Terracotta", "Ecru"], ["XS|Terracotta"]),
    clothingExtras: { material: "55% linen, 45% cotton", fit: "regular", care: "Gentle wash cold, line dry" },
  },
  // --- Hoodies (2) ---
  {
    id: "c06",
    slug: "heavyweight-fleece-hoodie",
    brand: "Pace Studio",
    name: "Heavyweight Fleece Hoodie",
    productType: "clothing",
    category: "clothing",
    subcategory: "hoodies",
    gender: "unisex",
    price: 2199,
    rating: 4.7,
    reviewCount: 143,
    badge: "new",
    stock: "in_stock",
    tags: ["fleece", "hoodie", "streetwear", "unisex"],
    description:
      "A brushed-back fleece hoodie with a boxy street cut and a double-lined hood that actually holds its shape. Substantial enough for winter, soft enough to live in.",
    features: ["380 GSM brushed fleece", "Double-lined hood", "Kangaroo pocket"],
    images: { main: "/images/products/heavyweight-fleece-hoodie-a.jpg", alt: "/images/products/heavyweight-fleece-hoodie-b.jpg" },
    colors: [
      { name: "Ink", hex: "#191919" },
      { name: "Oat", hex: "#d8cdb8" },
      { name: "Forest", hex: "#3f4a3c" },
    ],
    sizeType: "alpha",
    variants: variants(ALPHA, ["Ink", "Oat", "Forest"], ["XS|Forest"], ["S|Oat"]),
    clothingExtras: { material: "80% cotton, 20% polyester fleece", fit: "oversized", care: "Wash inside out cold, tumble low" },
  },
  {
    id: "c07",
    slug: "velocity-zip-through-hoodie",
    brand: "Velocity",
    name: "Velocity Zip-Through Hoodie",
    productType: "clothing",
    category: "clothing",
    subcategory: "hoodies",
    gender: "men",
    price: 2499,
    compareAtPrice: 2999,
    rating: 4.5,
    reviewCount: 68,
    badge: "sale",
    stock: "in_stock",
    tags: ["zip hoodie", "training", "layering", "activewear"],
    description:
      "A lightweight zip-through built as a training mid-layer, with a slim athletic cut that sits close without restricting. Zip hand pockets keep essentials secure on the move.",
    features: ["French-terry knit", "Full-length YKK zip", "Zip-secured pockets"],
    images: { main: "/images/products/velocity-zip-through-hoodie-a.jpg", alt: "/images/products/velocity-zip-through-hoodie-b.jpg" },
    colors: [
      { name: "Charcoal", hex: "#3a3a3a" },
      { name: "Racing Red", hex: "#d64045" },
    ],
    sizeType: "alpha",
    variants: variants(ALPHA, ["Charcoal", "Racing Red"], [], ["XL|Racing Red"]),
    clothingExtras: { material: "70% cotton, 30% polyester terry", fit: "slim", care: "Machine wash cold, close zip before wash" },
  },
  // --- Jeans (2) ---
  {
    id: "c08",
    slug: "slim-tapered-jeans",
    brand: "Pace Studio",
    name: "Slim Tapered Jeans",
    productType: "clothing",
    category: "clothing",
    subcategory: "jeans",
    gender: "men",
    price: 2499,
    rating: 4.4,
    reviewCount: 89,
    stock: "in_stock",
    tags: ["denim", "slim", "tapered", "stretch"],
    description:
      "A slim-tapered jean in comfort-stretch denim that keeps a clean line from thigh to ankle. Enough give for all-day wear, enough structure to stay sharp.",
    features: ["Comfort-stretch denim", "Tapered leg", "Reinforced belt loops"],
    images: { main: "/images/products/slim-tapered-jeans-a.jpg", alt: "/images/products/slim-tapered-jeans-b.jpg" },
    colors: [
      { name: "Mid Indigo", hex: "#3f5876" },
      { name: "Washed Black", hex: "#2b2b2e" },
    ],
    sizeType: "numeric",
    variants: variants(JEANS, ["Mid Indigo", "Washed Black"], ["28|Washed Black"], ["36|Mid Indigo"]),
    clothingExtras: { material: "98% cotton, 2% elastane", fit: "slim", care: "Wash inside out cold, hang dry" },
  },
  {
    id: "c09",
    slug: "high-rise-straight-jeans-women",
    brand: "Pace Studio",
    name: "High-Rise Straight Jeans",
    productType: "clothing",
    category: "clothing",
    subcategory: "jeans",
    gender: "women",
    price: 2699,
    compareAtPrice: 3299,
    rating: 4.6,
    reviewCount: 71,
    badge: "sale",
    stock: "in_stock",
    tags: ["denim", "high rise", "straight leg", "women"],
    description:
      "A high-rise straight jean with a clean vintage-inspired line and a firm, structured denim that holds you in. Cropped just above the ankle to show off your footwear.",
    features: ["Rigid vintage-wash denim", "High-rise waist", "Ankle-cropped straight leg"],
    images: { main: "/images/products/high-rise-straight-jeans-women-a.jpg", alt: "/images/products/high-rise-straight-jeans-women-b.jpg" },
    colors: [
      { name: "Light Wash", hex: "#8fa6bd" },
      { name: "Ecru", hex: "#e8e2d5" },
    ],
    sizeType: "numeric",
    variants: variants(["26", "28", "30", "32", "34"], ["Light Wash", "Ecru"], ["26|Ecru"], ["34|Ecru"]),
    clothingExtras: { material: "100% cotton denim", fit: "regular", care: "Wash cold with like colours, hang dry" },
  },
  // --- Trousers (1) ---
  {
    id: "c10",
    slug: "tech-jogger-trousers",
    brand: "Velocity",
    name: "Tech Jogger Trousers",
    productType: "clothing",
    category: "clothing",
    subcategory: "trousers",
    gender: "unisex",
    price: 2299,
    rating: 4.5,
    reviewCount: 57,
    badge: "new",
    stock: "in_stock",
    tags: ["joggers", "tech", "tapered", "travel"],
    description:
      "A tapered tech-jogger in a four-way stretch weave with a drawcord waist and zip cuffs. Wrinkle-resistant and travel-ready, it looks tidy far beyond the gym.",
    features: ["4-way stretch woven fabric", "Zip ankle cuffs", "Hidden zip pocket"],
    images: { main: "/images/products/tech-jogger-trousers-a.jpg", alt: "/images/products/tech-jogger-trousers-b.jpg" },
    colors: [
      { name: "Ink", hex: "#191919" },
      { name: "Stone", hex: "#a9a294" },
    ],
    sizeType: "alpha",
    variants: variants(ALPHA, ["Ink", "Stone"], [], ["XS|Stone"]),
    clothingExtras: { material: "92% nylon, 8% elastane", fit: "slim", care: "Machine wash cold, do not tumble dry" },
  },
  // --- Jackets (1) ---
  {
    id: "c11",
    slug: "monsoon-shell-jacket",
    brand: "Velocity",
    name: "Monsoon Shell Jacket",
    productType: "clothing",
    category: "clothing",
    subcategory: "jackets",
    gender: "unisex",
    price: 4499,
    compareAtPrice: 5999,
    rating: 4.8,
    reviewCount: 44,
    badge: "sale",
    stock: "low",
    tags: ["jacket", "waterproof", "monsoon", "shell", "outerwear"],
    description:
      "A packable water-resistant shell built for city monsoons, with taped seams and a stowaway hood. Lightweight enough to carry every day, tough enough to trust in a downpour.",
    features: ["Water-resistant ripstop", "Taped seams", "Packs into its own pocket"],
    images: { main: "/images/products/monsoon-shell-jacket-a.jpg", alt: "/images/products/monsoon-shell-jacket-b.jpg" },
    colors: [
      { name: "Ink", hex: "#191919" },
      { name: "Racing Red", hex: "#d64045" },
      { name: "Olive", hex: "#5f6248" },
    ],
    sizeType: "alpha",
    variants: variants(ALPHA, ["Ink", "Racing Red", "Olive"], ["XS|Racing Red", "XXL|Olive"], ["S|Racing Red", "M|Olive"]),
    clothingExtras: { material: "100% nylon ripstop, PU coating", fit: "regular", care: "Wipe clean, do not machine wash" },
  },
  // --- Dresses (1) ---
  {
    id: "c12",
    slug: "everyday-jersey-midi-dress",
    brand: "Pace Studio",
    name: "Everyday Jersey Midi Dress",
    productType: "clothing",
    category: "clothing",
    subcategory: "dresses",
    gender: "women",
    price: 2499,
    rating: 4.7,
    reviewCount: 63,
    badge: "new",
    stock: "in_stock",
    tags: ["dress", "midi", "jersey", "women", "everyday"],
    description:
      "A ribbed-jersey midi with a flattering scoop neck and a skirt that skims rather than clings. It dresses up with heels or down with sneakers in seconds.",
    features: ["Stretch ribbed jersey", "Scoop neckline", "Midi length with side slit"],
    images: { main: "/images/products/everyday-jersey-midi-dress-a.jpg", alt: "/images/products/everyday-jersey-midi-dress-b.jpg" },
    colors: [
      { name: "Ink", hex: "#191919" },
      { name: "Clay", hex: "#b26a55" },
    ],
    sizeType: "alpha",
    variants: variants(["XS", "S", "M", "L", "XL"], ["Ink", "Clay"], ["XL|Clay"]),
    clothingExtras: { material: "95% viscose, 5% elastane", fit: "slim", care: "Hand wash cold, dry flat" },
  },
  // --- Activewear (1) ---
  {
    id: "c13",
    slug: "velocity-training-shorts",
    brand: "Velocity",
    name: "Velocity 7\" Training Shorts",
    productType: "clothing",
    category: "clothing",
    subcategory: "activewear",
    gender: "men",
    price: 1299,
    compareAtPrice: 1699,
    rating: 4.3,
    reviewCount: 38,
    badge: "sale",
    stock: "in_stock",
    tags: ["shorts", "training", "activewear", "gym", "running"],
    description:
      "Lightweight 7-inch training shorts with a built-in liner and a zip pocket that stays put during runs. The quick-dry weave keeps things cool when the session heats up.",
    features: ["Quick-dry woven shell", "Built-in mesh liner", "Zip back pocket"],
    images: { main: "/images/products/velocity-training-shorts-a.jpg", alt: "/images/products/velocity-training-shorts-b.jpg" },
    colors: [
      { name: "Ink", hex: "#191919" },
      { name: "Slate", hex: "#5a5f66" },
    ],
    sizeType: "alpha",
    variants: variants(ALPHA, ["Ink", "Slate"], [], ["XXL|Slate"]),
    clothingExtras: { material: "100% recycled polyester", fit: "regular", care: "Machine wash cold, tumble low" },
  },
  // --- Kids clothing (1) ---
  {
    id: "c14",
    slug: "pacekids-graphic-tee",
    brand: "PaceKids",
    name: "PaceKids Graphic Tee",
    productType: "clothing",
    category: "clothing",
    subcategory: "kids clothing",
    gender: "kids",
    price: 599,
    compareAtPrice: 799,
    rating: 4.6,
    reviewCount: 41,
    badge: "sale",
    stock: "in_stock",
    tags: ["kids", "tee", "cotton", "graphic"],
    description:
      "A soft cotton tee with a cheerful speed-mark print that kids actually want to wear. Roomy through the body for easy movement and endless play.",
    features: ["Soft 100% cotton", "Fade-resistant print", "Tagless neck for comfort"],
    images: { main: "/images/products/pacekids-graphic-tee-a.jpg", alt: "/images/products/pacekids-graphic-tee-b.jpg" },
    colors: [
      { name: "Sky", hex: "#b9cdda" },
      { name: "Racing Red", hex: "#d64045" },
    ],
    sizeType: "alpha",
    variants: variants(ALPHA_KID, ["Sky", "Racing Red"], ["3-4Y|Racing Red"], ["11-12Y|Sky"]),
    clothingExtras: { material: "100% cotton", fit: "regular", care: "Machine wash cold, tumble dry low" },
  },

  /* ============================ FOOTWEAR (12) ============================ */
  // --- Sneakers (3) ---
  {
    id: "f01",
    slug: "urbankicks-court-low",
    brand: "UrbanKicks",
    name: "Court Low Sneaker",
    productType: "footwear",
    category: "footwear",
    subcategory: "sneakers",
    gender: "unisex",
    price: 3499,
    rating: 4.7,
    reviewCount: 212,
    badge: "new",
    stock: "in_stock",
    tags: ["sneakers", "court", "low top", "leather", "everyday"],
    description:
      "A clean court-style low top in tumbled leather that goes with everything from jeans to joggers. A cushioned footbed keeps all-day city wear comfortable underfoot.",
    features: ["Tumbled leather upper", "Cushioned OrthoLite footbed", "Rubber cupsole"],
    images: { main: "/images/products/urbankicks-court-low-a.jpg", alt: "/images/products/urbankicks-court-low-b.jpg" },
    colors: [
      { name: "White", hex: "#f4f2ec" },
      { name: "Ink", hex: "#191919" },
    ],
    sizeType: "shoe",
    variants: variants(SHOE_ADULT, ["White", "Ink"], ["6|Ink"], ["12|White"]),
    footwearExtras: { upper: "Tumbled leather", sole: "Vulcanised rubber cupsole", closure: "Lace-up", use: "Everyday / casual" },
  },
  {
    id: "f02",
    slug: "urbankicks-retro-runner",
    brand: "UrbanKicks",
    name: "Retro Runner Sneaker",
    productType: "footwear",
    category: "footwear",
    subcategory: "sneakers",
    gender: "men",
    price: 4299,
    compareAtPrice: 5499,
    rating: 4.6,
    reviewCount: 156,
    badge: "sale",
    stock: "in_stock",
    tags: ["sneakers", "retro", "runner", "suede", "streetwear"],
    description:
      "A retro-inspired runner mixing suede and mesh over a chunky EVA wedge for that late-90s silhouette. Comfortable enough to walk in all day, styled to stand out.",
    features: ["Suede and mesh upper", "EVA wedge midsole", "Gum rubber outsole"],
    images: { main: "/images/products/urbankicks-retro-runner-a.jpg", alt: "/images/products/urbankicks-retro-runner-b.jpg" },
    colors: [
      { name: "Sand", hex: "#d9cbb3" },
      { name: "Navy", hex: "#28324a" },
    ],
    sizeType: "shoe",
    variants: variants(SHOE_ADULT, ["Sand", "Navy"], ["6|Navy"], ["11|Sand", "12|Navy"]),
    footwearExtras: { upper: "Suede & breathable mesh", sole: "EVA + gum rubber", closure: "Lace-up", use: "Casual / streetwear" },
  },
  {
    id: "f03",
    slug: "urbankicks-canvas-slip-on",
    brand: "UrbanKicks",
    name: "Canvas Slip-On Sneaker",
    productType: "footwear",
    category: "footwear",
    subcategory: "sneakers",
    gender: "women",
    price: 2499,
    rating: 4.4,
    reviewCount: 88,
    stock: "in_stock",
    tags: ["sneakers", "slip-on", "canvas", "summer"],
    description:
      "An easy canvas slip-on with elastic side gores and a padded collar for grab-and-go mornings. The low-profile sole keeps the look neat and summer-ready.",
    features: ["Cotton canvas upper", "Elastic side gores", "Padded collar"],
    images: { main: "/images/products/urbankicks-canvas-slip-on-a.jpg", alt: "/images/products/urbankicks-canvas-slip-on-b.jpg" },
    colors: [
      { name: "Ecru", hex: "#e8e2d5" },
      { name: "Ink", hex: "#191919" },
    ],
    sizeType: "shoe",
    variants: variants(["5", "6", "7", "8", "9", "10"], ["Ecru", "Ink"], [], ["5|Ecru"]),
    footwearExtras: { upper: "Cotton canvas", sole: "Vulcanised rubber", closure: "Slip-on", use: "Casual / everyday" },
  },
  // --- Running (3) ---
  {
    id: "f04",
    slug: "velocity-glide-running",
    brand: "Velocity",
    name: "Glide Cushion Running Shoe",
    productType: "footwear",
    category: "footwear",
    subcategory: "running",
    gender: "men",
    price: 5499,
    compareAtPrice: 6999,
    rating: 4.8,
    reviewCount: 174,
    badge: "sale",
    stock: "in_stock",
    tags: ["running", "cushioned", "training", "road"],
    description:
      "A daily-trainer built for soft, springy landings over long road miles, with an energy-return foam core. A breathable engineered mesh keeps feet cool at tempo.",
    features: ["High-rebound foam midsole", "Engineered mesh upper", "Carbon-rubber outsole"],
    images: { main: "/images/products/velocity-glide-running-a.jpg", alt: "/images/products/velocity-glide-running-b.jpg" },
    colors: [
      { name: "Racing Red", hex: "#d64045" },
      { name: "Ink", hex: "#191919" },
    ],
    sizeType: "shoe",
    variants: variants(SHOE_ADULT, ["Racing Red", "Ink"], ["12|Racing Red"], ["6|Racing Red"]),
    footwearExtras: { upper: "Engineered mesh", sole: "Energy-return foam + carbon rubber", closure: "Lace-up", use: "Road running / training" },
  },
  {
    id: "f05",
    slug: "velocity-trail-grip",
    brand: "Velocity",
    name: "Trail Grip Running Shoe",
    productType: "footwear",
    category: "footwear",
    subcategory: "running",
    gender: "unisex",
    price: 6499,
    rating: 4.7,
    reviewCount: 96,
    badge: "new",
    stock: "in_stock",
    tags: ["running", "trail", "grip", "outdoor"],
    description:
      "A trail runner with an aggressive lugged outsole that bites into loose ground and wet rock. A protective toe cap and rock plate shield feet on rough terrain.",
    features: ["Multi-directional lug outsole", "Reinforced toe cap", "Rock-plate underfoot"],
    images: { main: "/images/products/velocity-trail-grip-a.jpg", alt: "/images/products/velocity-trail-grip-b.jpg" },
    colors: [
      { name: "Olive", hex: "#5f6248" },
      { name: "Ink", hex: "#191919" },
    ],
    sizeType: "shoe",
    variants: variants(SHOE_ADULT, ["Olive", "Ink"], [], ["12|Olive"]),
    footwearExtras: { upper: "Abrasion-resistant mesh", sole: "Lugged rubber + rock plate", closure: "Lace-up", use: "Trail running / hiking" },
  },
  {
    id: "f06",
    slug: "velocity-tempo-racer",
    brand: "Velocity",
    name: "Tempo Racer Running Shoe",
    productType: "footwear",
    category: "footwear",
    subcategory: "running",
    gender: "women",
    price: 7499,
    rating: 4.9,
    reviewCount: 61,
    badge: "new",
    stock: "low",
    tags: ["running", "racing", "lightweight", "tempo"],
    description:
      "A featherweight racer tuned for tempo runs and race day, with a propulsive plate for snappy toe-off. Every gram is stripped back so you can chase a personal best.",
    features: ["Propulsion plate", "Sub-200g lightweight build", "Breathable race mesh"],
    images: { main: "/images/products/velocity-tempo-racer-a.jpg", alt: "/images/products/velocity-tempo-racer-b.jpg" },
    colors: [
      { name: "Coral", hex: "#e07a5f" },
      { name: "Ink", hex: "#191919" },
    ],
    sizeType: "shoe",
    variants: variants(["5", "6", "7", "8", "9", "10"], ["Coral", "Ink"], ["5|Ink"], ["10|Coral", "9|Ink"]),
    footwearExtras: { upper: "Race-weight mesh", sole: "Propulsion plate + foam", closure: "Lace-up", use: "Racing / tempo runs" },
  },
  // --- Casual (2) ---
  {
    id: "f07",
    slug: "pace-suede-desert-boot",
    brand: "Pace Studio",
    name: "Suede Desert Shoe",
    productType: "footwear",
    category: "footwear",
    subcategory: "casual",
    gender: "men",
    price: 3999,
    rating: 4.5,
    reviewCount: 73,
    stock: "in_stock",
    tags: ["casual", "suede", "desert", "smart casual"],
    description:
      "A low desert-style shoe in soft suede on a natural crepe sole that softens every step. Smart enough for the office, easy enough for the weekend.",
    features: ["Soft suede upper", "Natural crepe sole", "Two-eyelet lacing"],
    images: { main: "/images/products/pace-suede-desert-boot-a.jpg", alt: "/images/products/pace-suede-desert-boot-b.jpg" },
    colors: [
      { name: "Sand", hex: "#d9cbb3" },
      { name: "Chocolate", hex: "#5a4130" },
    ],
    sizeType: "shoe",
    variants: variants(SHOE_ADULT, ["Sand", "Chocolate"], ["6|Chocolate"], ["12|Sand"]),
    footwearExtras: { upper: "Suede leather", sole: "Natural crepe rubber", closure: "Lace-up", use: "Smart casual" },
  },
  {
    id: "f08",
    slug: "urbankicks-canvas-hi-top",
    brand: "UrbanKicks",
    name: "Canvas Hi-Top",
    productType: "footwear",
    category: "footwear",
    subcategory: "casual",
    gender: "unisex",
    price: 2799,
    compareAtPrice: 3499,
    rating: 4.3,
    reviewCount: 64,
    badge: "sale",
    stock: "in_stock",
    tags: ["casual", "hi-top", "canvas", "classic"],
    description:
      "A classic lace-up hi-top in durable canvas with an ankle patch and vulcanised sole. A timeless silhouette that pairs with denim, shorts, or a dress.",
    features: ["Heavy cotton canvas", "Vulcanised rubber sole", "Metal eyelets"],
    images: { main: "/images/products/urbankicks-canvas-hi-top-a.jpg", alt: "/images/products/urbankicks-canvas-hi-top-b.jpg" },
    colors: [
      { name: "Ink", hex: "#191919" },
      { name: "Ecru", hex: "#e8e2d5" },
    ],
    sizeType: "shoe",
    variants: variants(SHOE_ADULT, ["Ink", "Ecru"], [], ["11|Ecru", "12|Ecru"]),
    footwearExtras: { upper: "Cotton canvas", sole: "Vulcanised rubber", closure: "Lace-up", use: "Casual / everyday" },
  },
  // --- Formal (2) ---
  {
    id: "f09",
    slug: "pace-leather-derby",
    brand: "Pace Studio",
    name: "Leather Derby Shoe",
    productType: "footwear",
    category: "footwear",
    subcategory: "formal",
    gender: "men",
    price: 4999,
    rating: 4.6,
    reviewCount: 49,
    stock: "in_stock",
    tags: ["formal", "leather", "derby", "office", "wedding"],
    description:
      "A polished derby in full-grain leather with a sleek almond toe for boardrooms and celebrations alike. A leather-lined interior breaks in beautifully over time.",
    features: ["Full-grain leather upper", "Leather lining", "Cushioned insole"],
    images: { main: "/images/products/pace-leather-derby-a.jpg", alt: "/images/products/pace-leather-derby-b.jpg" },
    colors: [
      { name: "Black", hex: "#1c1c1c" },
      { name: "Tan", hex: "#a76b3f" },
    ],
    sizeType: "shoe",
    variants: variants(SHOE_ADULT, ["Black", "Tan"], ["6|Tan"], ["12|Tan"]),
    footwearExtras: { upper: "Full-grain leather", sole: "TPR resin sole", closure: "Lace-up derby", use: "Formal / occasion" },
  },
  {
    id: "f10",
    slug: "pace-leather-loafer",
    brand: "Pace Studio",
    name: "Leather Penny Loafer",
    productType: "footwear",
    category: "footwear",
    subcategory: "formal",
    gender: "women",
    price: 3799,
    compareAtPrice: 4799,
    rating: 4.7,
    reviewCount: 58,
    badge: "sale",
    stock: "in_stock",
    tags: ["formal", "loafer", "leather", "slip-on", "smart"],
    description:
      "A refined penny loafer in smooth leather with a low block heel that works from desk to dinner. The slip-on ease belies just how put-together it looks.",
    features: ["Smooth leather upper", "Low block heel", "Signature penny strap"],
    images: { main: "/images/products/pace-leather-loafer-a.jpg", alt: "/images/products/pace-leather-loafer-b.jpg" },
    colors: [
      { name: "Black", hex: "#1c1c1c" },
      { name: "Burgundy", hex: "#6a2733" },
    ],
    sizeType: "shoe",
    variants: variants(["5", "6", "7", "8", "9", "10"], ["Black", "Burgundy"], ["5|Burgundy"], ["10|Burgundy"]),
    footwearExtras: { upper: "Smooth leather", sole: "Leather-look TPR sole", closure: "Slip-on", use: "Smart / office" },
  },
  // --- Boots (1) ---
  {
    id: "f11",
    slug: "pace-chelsea-boot",
    brand: "Pace Studio",
    name: "Leather Chelsea Boot",
    productType: "footwear",
    category: "footwear",
    subcategory: "boots",
    gender: "unisex",
    price: 5999,
    compareAtPrice: 7499,
    rating: 4.8,
    reviewCount: 87,
    badge: "sale",
    stock: "low",
    tags: ["boots", "chelsea", "leather", "winter"],
    description:
      "A clean Chelsea boot in burnished leather with twin elastic gussets for easy pull-on wear. A lugged sole adds grip and an all-weather edge to a timeless shape.",
    features: ["Burnished leather upper", "Twin elastic side gussets", "Lugged rubber sole"],
    images: { main: "/images/products/pace-chelsea-boot-a.jpg", alt: "/images/products/pace-chelsea-boot-b.jpg" },
    colors: [
      { name: "Chocolate", hex: "#5a4130" },
      { name: "Black", hex: "#1c1c1c" },
    ],
    sizeType: "shoe",
    variants: variants(SHOE_ADULT, ["Chocolate", "Black"], ["6|Chocolate", "12|Black"], ["11|Chocolate"]),
    footwearExtras: { upper: "Burnished leather", sole: "Lugged rubber", closure: "Pull-on elastic", use: "Everyday / winter" },
  },
  // --- Sandals (1) + Kids footwear folded here to hit 12 ---
  {
    id: "f12",
    slug: "pacekids-play-sneaker",
    brand: "PaceKids",
    name: "PaceKids Play Sneaker",
    productType: "footwear",
    category: "footwear",
    subcategory: "kids footwear",
    gender: "kids",
    price: 1499,
    compareAtPrice: 1899,
    rating: 4.6,
    reviewCount: 52,
    badge: "sale",
    stock: "in_stock",
    tags: ["kids", "sneakers", "velcro", "school", "play"],
    description:
      "A lightweight kids' sneaker with easy hook-and-loop straps little hands can manage themselves. A flexible, grippy sole keeps up with the playground all day.",
    features: ["Easy hook-and-loop straps", "Flexible grippy sole", "Washable lining"],
    images: { main: "/images/products/pacekids-play-sneaker-a.jpg", alt: "/images/products/pacekids-play-sneaker-b.jpg" },
    colors: [
      { name: "Racing Red", hex: "#d64045" },
      { name: "Sky", hex: "#b9cdda" },
    ],
    sizeType: "shoe",
    variants: variants(SHOE_KID, ["Racing Red", "Sky"], ["10|Sky"], ["2|Racing Red"]),
    footwearExtras: { upper: "Breathable mesh & synthetic", sole: "Flexible EVA rubber", closure: "Hook-and-loop", use: "School / play" },
  },
  {
    id: "f13",
    slug: "pace-comfort-sandal",
    brand: "Pace Studio",
    name: "Comfort Footbed Sandal",
    productType: "footwear",
    category: "footwear",
    subcategory: "sandals",
    gender: "unisex",
    price: 1799,
    rating: 4.4,
    reviewCount: 47,
    stock: "in_stock",
    tags: ["sandals", "summer", "footbed", "casual"],
    description:
      "A two-strap sandal on a contoured cork-look footbed that moulds to your step over time. Adjustable buckles dial in the fit for lazy summer days.",
    features: ["Contoured footbed", "Adjustable buckles", "Grippy EVA outsole"],
    images: { main: "/images/products/pace-comfort-sandal-a.jpg", alt: "/images/products/pace-comfort-sandal-b.jpg" },
    colors: [
      { name: "Tan", hex: "#a76b3f" },
      { name: "Ink", hex: "#191919" },
    ],
    sizeType: "shoe",
    variants: variants(["5", "6", "7", "8", "9", "10", "11"], ["Tan", "Ink"], [], ["11|Tan"]),
    footwearExtras: { upper: "Synthetic strap", sole: "Cork-look EVA footbed", closure: "Buckle straps", use: "Summer / casual" },
  },

  /* ============================ ACCESSORIES (6) ============================ */
  {
    id: "a01",
    slug: "pace-daily-tote",
    brand: "Pace Studio",
    name: "Daily Canvas Tote",
    productType: "accessories",
    category: "accessories",
    subcategory: "bags",
    gender: "unisex",
    price: 1499,
    compareAtPrice: 1999,
    rating: 4.5,
    reviewCount: 69,
    badge: "sale",
    stock: "in_stock",
    tags: ["bag", "tote", "canvas", "everyday"],
    description:
      "A structured heavyweight-canvas tote roomy enough for a laptop, gym kit, or the day's shopping. An interior zip pocket keeps small essentials from getting lost.",
    features: ["16 oz heavy canvas", "Interior zip pocket", "Reinforced handles"],
    images: { main: "/images/products/pace-daily-tote-a.jpg" },
    colors: [
      { name: "Ecru", hex: "#e8e2d5" },
      { name: "Ink", hex: "#191919" },
    ],
    variants: [
      { size: "One Size", color: "Ecru", stock: "in_stock" },
      { size: "One Size", color: "Ink", stock: "in_stock" },
    ],
    accessoryExtras: { material: "16 oz cotton canvas", dimensions: "38 × 40 × 12 cm", details: "Interior zip pocket, 30cm handle drop" },
  },
  {
    id: "a02",
    slug: "velocity-crossbody-sling",
    brand: "Velocity",
    name: "Velocity Crossbody Sling",
    productType: "accessories",
    category: "accessories",
    subcategory: "bags",
    gender: "unisex",
    price: 1299,
    rating: 4.4,
    reviewCount: 55,
    badge: "new",
    stock: "in_stock",
    tags: ["bag", "sling", "crossbody", "travel"],
    description:
      "A compact crossbody sling in water-resistant nylon for phone, wallet, and keys on the move. The adjustable strap wears across the chest or over the shoulder.",
    features: ["Water-resistant nylon", "Adjustable strap", "Two zip compartments"],
    images: { main: "/images/products/velocity-crossbody-sling-a.jpg" },
    colors: [
      { name: "Ink", hex: "#191919" },
      { name: "Racing Red", hex: "#d64045" },
    ],
    variants: [
      { size: "One Size", color: "Ink", stock: "in_stock" },
      { size: "One Size", color: "Racing Red", stock: "low" },
    ],
    accessoryExtras: { material: "Water-resistant nylon", dimensions: "22 × 15 × 6 cm", details: "Two zip compartments, adjustable strap" },
  },
  {
    id: "a03",
    slug: "pace-6panel-cap",
    brand: "Pace Studio",
    name: "6-Panel Cotton Cap",
    productType: "accessories",
    category: "accessories",
    subcategory: "caps",
    gender: "unisex",
    price: 799,
    rating: 4.3,
    reviewCount: 42,
    stock: "in_stock",
    tags: ["cap", "hat", "cotton", "everyday"],
    description:
      "A classic six-panel cap in washed cotton twill with a curved brim and adjustable strap. A subtle embroidered speed-mark keeps it low-key.",
    features: ["Washed cotton twill", "Adjustable metal buckle", "Pre-curved brim"],
    images: { main: "/images/products/pace-6panel-cap-a.jpg" },
    colors: [
      { name: "Ink", hex: "#191919" },
      { name: "Sand", hex: "#d9cbb3" },
      { name: "Racing Red", hex: "#d64045" },
    ],
    variants: [
      { size: "One Size", color: "Ink", stock: "in_stock" },
      { size: "One Size", color: "Sand", stock: "in_stock" },
      { size: "One Size", color: "Racing Red", stock: "in_stock" },
    ],
    accessoryExtras: { material: "100% washed cotton twill", dimensions: "Adjustable 54–60 cm", details: "Embroidered speed-mark, metal buckle" },
  },
  {
    id: "a04",
    slug: "pace-leather-belt",
    brand: "Pace Studio",
    name: "Full-Grain Leather Belt",
    productType: "accessories",
    category: "accessories",
    subcategory: "belts",
    gender: "men",
    price: 1199,
    compareAtPrice: 1499,
    rating: 4.6,
    reviewCount: 37,
    badge: "sale",
    stock: "in_stock",
    tags: ["belt", "leather", "formal", "everyday"],
    description:
      "A 35mm full-grain leather belt with a brushed nickel buckle that dresses up or down with ease. Edge-painted and stitched to last for years.",
    features: ["Full-grain leather", "Brushed nickel buckle", "Edge-painted finish"],
    images: { main: "/images/products/pace-leather-belt-a.jpg" },
    colors: [
      { name: "Black", hex: "#1c1c1c" },
      { name: "Tan", hex: "#a76b3f" },
    ],
    sizeType: "numeric",
    variants: variants(["30", "32", "34", "36", "38"], ["Black", "Tan"], ["30|Tan"], ["38|Tan"]),
    accessoryExtras: { material: "Full-grain leather", dimensions: "35 mm width", details: "Brushed nickel buckle, edge-painted" },
  },
  {
    id: "a05",
    slug: "pace-bifold-wallet",
    brand: "Pace Studio",
    name: "Slim Bifold Wallet",
    productType: "accessories",
    category: "accessories",
    subcategory: "wallets",
    gender: "unisex",
    price: 999,
    rating: 4.5,
    reviewCount: 61,
    badge: "new",
    stock: "low",
    tags: ["wallet", "leather", "bifold", "slim"],
    description:
      "A slim bifold in soft leather with six card slots and a full-length note compartment. Trim enough to sit flat in a front pocket without the bulk.",
    features: ["Soft leather build", "Six card slots", "RFID-blocking lining"],
    images: { main: "/images/products/pace-bifold-wallet-a.jpg" },
    colors: [
      { name: "Black", hex: "#1c1c1c" },
      { name: "Chocolate", hex: "#5a4130" },
    ],
    variants: [
      { size: "One Size", color: "Black", stock: "in_stock" },
      { size: "One Size", color: "Chocolate", stock: "low" },
    ],
    accessoryExtras: { material: "Soft full-grain leather", dimensions: "11 × 9 cm folded", details: "6 card slots, RFID-blocking lining" },
  },
  {
    id: "a06",
    slug: "pace-city-sunglasses",
    brand: "Pace Studio",
    name: "City Sunglasses",
    productType: "accessories",
    category: "accessories",
    subcategory: "sunglasses",
    gender: "unisex",
    price: 1699,
    compareAtPrice: 2199,
    rating: 4.4,
    reviewCount: 45,
    badge: "sale",
    stock: "in_stock",
    tags: ["sunglasses", "uv", "acetate", "summer"],
    description:
      "A slim acetate frame with a slightly squared silhouette that flatters most face shapes. Polarised lenses cut glare with full UV400 protection for bright city days.",
    features: ["Polarised UV400 lenses", "Lightweight acetate frame", "Spring hinges"],
    images: { main: "/images/products/pace-city-sunglasses-a.jpg" },
    colors: [
      { name: "Tortoise", hex: "#6a4a2a" },
      { name: "Ink", hex: "#191919" },
    ],
    variants: [
      { size: "One Size", color: "Tortoise", stock: "in_stock" },
      { size: "One Size", color: "Ink", stock: "in_stock" },
    ],
    accessoryExtras: { material: "Acetate frame, polycarbonate lens", dimensions: "145 mm frame width", details: "Polarised UV400, spring hinges, case included" },
  },
];

/* -----------------------------------------------------------
   Derived helpers / data-layer functions (backend-swappable)
   ----------------------------------------------------------- */
export function getAllProducts(): Product[] {
  return products;
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByType(type: Product["productType"]): Product[] {
  return products.filter((p) => p.productType === type);
}

export function getSaleProducts(): Product[] {
  return products.filter((p) => p.badge === "sale" || p.compareAtPrice);
}

export function getNewProducts(): Product[] {
  return products.filter((p) => p.badge === "new");
}

export function getSizesForProduct(p: Product): string[] {
  return Array.from(new Set(p.variants.map((v) => v.size)));
}

export function getColorsForProduct(p: Product): string[] {
  return Array.from(new Set(p.variants.map((v) => v.color)));
}

export function isVariantAvailable(p: Product, size: string, color: string): boolean {
  const v = p.variants.find((x) => x.size === size && x.color === color);
  return !!v && v.stock !== "out";
}

export function getVariant(p: Product, size: string, color: string) {
  return p.variants.find((x) => x.size === size && x.color === color);
}

export function discountPercent(p: Product): number | null {
  if (!p.compareAtPrice || p.compareAtPrice <= p.price) return null;
  return Math.round(((p.compareAtPrice - p.price) / p.compareAtPrice) * 100);
}
